spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ace
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

